import { MeliResponse } from './services/useMercadolibreService'

export const MOCKED_MELI_RESPONSE: MeliResponse = {
    site_id: 'MLU',
    paging: {
        total: 1,
        offset: 0,
        limit: 1,
        primary_results: 1,
    },
    results: [
        {
            id: 'MLU811601010',
            site_id: 'MLU',
            title: 'iPhone 15 Dual Sim 512 Gb Negro',
            seller: {
                id: 451257294,
                power_seller_status: null,
                car_dealer: false,
                real_estate_agency: false,
                tags: [],
            },
            price: 39199, // Price in Uruguayan Pesos (UYU)
            currency_id: 'UYU',
            available_quantity: 1,
            sold_quantity: 1,
            buying_mode: 'buy_it_now',
            listing_type_id: 'gold_pro',
            stop_time: '2039-08-22T04:00:00.000Z',
            condition: 'new',
            permalink: 'https://www.mercadolibre.com.ar/p/MLU13550363',
            thumbnail: 'http://MLU-s1-p.mlstatic.com/943469-MLU31002769183_062019-I.jpg',
            accepts_mercadopago: true,
            installments: {
                quantity: 6,
                amount: 6999.83, // Monthly installment in UYU
                rate: 0,
                currency_id: 'UYU',
            },
            address: {
                state_id: 'AR-B',
                state_name: 'Buenos Aires',
                city_id: 'TUxBQ0dFTjY4NTg',
                city_name: 'General Rodríguez',
            },
            shipping: {
                free_shipping: true,
                mode: 'me2',
                tags: ['mandatory_free_shipping'],
                logistic_type: 'drop_off',
                store_pick_up: false,
            },
            seller_address: {
                country: {
                    id: 'AR',
                    name: 'Argentina',
                },
                state: {
                    id: 'AR-B',
                    name: 'Buenos Aires',
                },
                city: {
                    id: 'TUxBQ0dFTjY4NTg',
                    name: 'General Rodríguez',
                },
                latitude: '',
                longitude: '',
            },
            attributes: [
                {
                    values: [
                        {
                            source: 1,
                            id: '206',
                            name: 'Apple',
                            struct: null,
                        },
                    ],
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    id: 'BRAND',
                    value_id: '206',
                    value_name: 'Apple',
                    value_struct: null,
                    source: 1,
                    name: 'Marca',
                },
                {
                    id: 'CPU_MODEL',
                    value_struct: null,
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '7657686',
                            name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo de CPU',
                    value_id: '7657686',
                    value_name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                },
                {
                    values: [
                        {
                            name: 'Nuevo',
                            struct: null,
                            source: 8342579661593500,
                            id: '2230284',
                        },
                    ],
                    id: 'ITEM_CONDITION',
                    value_struct: null,
                    value_name: 'Nuevo',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 8342579661593500,
                    name: 'Condición del ítem',
                    value_id: '2230284',
                },
                {
                    value_id: '58993',
                    value_name: 'iPhone',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 1,
                    id: 'LINE',
                    name: 'Línea',
                    value_struct: null,
                    values: [
                        {
                            source: 1,
                            id: '58993',
                            name: 'iPhone',
                            struct: null,
                        },
                    ],
                },
                {
                    value_name: 'iPhone 15',
                    values: [
                        {
                            id: '6047739',
                            name: 'iPhone 15',
                            struct: null,
                            source: 1,
                        },
                    ],
                    id: 'MODEL',
                    name: 'Modelo',
                    value_id: '6047739',
                    source: 1,
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                },
                {
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '2087879',
                            name: 'Apple A15 Bionic',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo del procesador',
                    value_name: 'Apple A15 Bionic',
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                    id: 'PROCESSOR_MODEL',
                    value_id: '2087879',
                },
            ],
            differential_pricing: {
                id: 33669181,
            },
            original_price: null,
            category_id: 'MLU1055',
            official_store_id: null,
            catalog_product_id: 'MLU13550363',
            tags: [
                'extended_warranty_eligible',
                'good_quality_picture',
                'good_quality_thumbnail',
                'immediate_payment',
                'cart_eligible',
            ],
            catalog_listing: true,
        },
        {
            id: 'MLA811601011',
            site_id: 'MLA',
            title: 'Samsung Galaxy S22 Dual Sim 256 Gb Negro',
            seller: {
                id: 451257294,
                power_seller_status: null,
                car_dealer: false,
                real_estate_agency: false,
                tags: [],
            },
            price: 45999, // Price in Uruguayan Pesos (UYU)
            currency_id: 'UYU',
            available_quantity: 1,
            sold_quantity: 1,
            buying_mode: 'buy_it_now',
            listing_type_id: 'gold_pro',
            stop_time: '2039-08-22T04:00:00.000Z',
            condition: 'new',
            permalink: 'https://www.mercadolibre.com.ar/p/MLA13550364',
            thumbnail: 'http://mla-s1-p.mlstatic.com/943469-MLA31002769184_062019-I.jpg',
            accepts_mercadopago: true,
            installments: {
                quantity: 6,
                amount: 7666.5, // Monthly installment in UYU
                rate: 0,
                currency_id: 'UYU',
            },
            address: {
                state_id: 'AR-B',
                state_name: 'Buenos Aires',
                city_id: 'TUxBQ0dFTjY4NTg',
                city_name: 'General Rodríguez',
            },
            shipping: {
                free_shipping: true,
                mode: 'me2',
                tags: ['mandatory_free_shipping'],
                logistic_type: 'drop_off',
                store_pick_up: false,
            },
            seller_address: {
                country: {
                    id: 'AR',
                    name: 'Argentina',
                },
                state: {
                    id: 'AR-B',
                    name: 'Buenos Aires',
                },
                city: {
                    id: 'TUxBQ0dFTjY4NTg',
                    name: 'General Rodríguez',
                },
                latitude: '',
                longitude: '',
            },
            attributes: [
                {
                    values: [
                        {
                            source: 1,
                            id: '206',
                            name: 'Samsung',
                            struct: null,
                        },
                    ],
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    id: 'BRAND',
                    value_id: '206',
                    value_name: 'Samsung',
                    value_struct: null,
                    source: 1,
                    name: 'Marca',
                },
                {
                    id: 'CPU_MODEL',
                    value_struct: null,
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '7657686',
                            name: '4x2.8 GHz Cortex-X2/4x1.8 GHz Cortex-A53',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo de CPU',
                    value_id: '7657686',
                    value_name: '4x2.8 GHz Cortex-X2/4x1.8 GHz Cortex-A53',
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                },
                {
                    values: [
                        {
                            name: 'Nuevo',
                            struct: null,
                            source: 8342579661593500,
                            id: '2230284',
                        },
                    ],
                    id: 'ITEM_CONDITION',
                    value_struct: null,
                    value_name: 'Nuevo',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 8342579661593500,
                    name: 'Condición del ítem',
                    value_id: '2230284',
                },
                {
                    value_id: '195973',
                    value_name: 'Galaxy S',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 1,
                    id: 'LINE',
                    name: 'Línea',
                    value_struct: null,
                    values: [
                        {
                            source: 1,
                            id: '195973',
                            name: 'Galaxy S',
                            struct: null,
                        },
                    ],
                },
                {
                    value_name: 'Galaxy S22',
                    values: [
                        {
                            id: '6047739',
                            name: 'Galaxy S22',
                            struct: null,
                            source: 1,
                        },
                    ],
                    id: 'MODEL',
                    name: 'Modelo',
                    value_id: '6047739',
                    source: 1,
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                },
                {
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '2087879',
                            name: 'Exynos 2200',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo del procesador',
                    value_name: 'Exynos 2200',
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                    id: 'PROCESSOR_MODEL',
                    value_id: '2087879',
                },
            ],
            differential_pricing: {
                id: 33669182,
            },
            original_price: null,
            category_id: 'MLA1055',
            official_store_id: null,
            catalog_product_id: 'MLA13550364',
            tags: [
                'extended_warranty_eligible',
                'good_quality_picture',
                'good_quality_thumbnail',
                'immediate_payment',
                'cart_eligible',
            ],
            catalog_listing: true,
        },
        {
            id: 'MLU811601010',
            site_id: 'MLU',
            title: 'iPhone 15 Dual Sim 128 Gb Negro',
            seller: {
                id: 451257294,
                power_seller_status: null,
                car_dealer: false,
                real_estate_agency: false,
                tags: [],
            },
            price: 60010, // Price in Uruguayan Pesos (UYU)
            currency_id: 'UYU',
            available_quantity: 1,
            sold_quantity: 1,
            buying_mode: 'buy_it_now',
            listing_type_id: 'gold_pro',
            stop_time: '2039-08-22T04:00:00.000Z',
            condition: 'new',
            permalink: 'https://www.mercadolibre.com.ar/p/MLU13550363',
            thumbnail: 'http://MLU-s1-p.mlstatic.com/943469-MLU31002769183_062019-I.jpg',
            accepts_mercadopago: true,
            installments: {
                quantity: 6,
                amount: 6999.83, // Monthly installment in UYU
                rate: 0,
                currency_id: 'UYU',
            },
            address: {
                state_id: 'AR-B',
                state_name: 'Buenos Aires',
                city_id: 'TUxBQ0dFTjY4NTg',
                city_name: 'General Rodríguez',
            },
            shipping: {
                free_shipping: true,
                mode: 'me2',
                tags: ['mandatory_free_shipping'],
                logistic_type: 'drop_off',
                store_pick_up: false,
            },
            seller_address: {
                country: {
                    id: 'AR',
                    name: 'Argentina',
                },
                state: {
                    id: 'AR-B',
                    name: 'Buenos Aires',
                },
                city: {
                    id: 'TUxBQ0dFTjY4NTg',
                    name: 'General Rodríguez',
                },
                latitude: '',
                longitude: '',
            },
            attributes: [
                {
                    values: [
                        {
                            source: 1,
                            id: '206',
                            name: 'Apple',
                            struct: null,
                        },
                    ],
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    id: 'BRAND',
                    value_id: '206',
                    value_name: 'Apple',
                    value_struct: null,
                    source: 1,
                    name: 'Marca',
                },
                {
                    id: 'CPU_MODEL',
                    value_struct: null,
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '7657686',
                            name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo de CPU',
                    value_id: '7657686',
                    value_name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                },
                {
                    values: [
                        {
                            name: 'Nuevo',
                            struct: null,
                            source: 8342579661593500,
                            id: '2230284',
                        },
                    ],
                    id: 'ITEM_CONDITION',
                    value_struct: null,
                    value_name: 'Nuevo',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 8342579661593500,
                    name: 'Condición del ítem',
                    value_id: '2230284',
                },
                {
                    value_id: '58993',
                    value_name: 'iPhone',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 1,
                    id: 'LINE',
                    name: 'Línea',
                    value_struct: null,
                    values: [
                        {
                            source: 1,
                            id: '58993',
                            name: 'iPhone',
                            struct: null,
                        },
                    ],
                },
                {
                    value_name: 'iPhone 15',
                    values: [
                        {
                            id: '6047739',
                            name: 'iPhone 15',
                            struct: null,
                            source: 1,
                        },
                    ],
                    id: 'MODEL',
                    name: 'Modelo',
                    value_id: '6047739',
                    source: 1,
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                },
                {
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '2087879',
                            name: 'Apple A15 Bionic',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo del procesador',
                    value_name: 'Apple A15 Bionic',
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                    id: 'PROCESSOR_MODEL',
                    value_id: '2087879',
                },
            ],
            differential_pricing: {
                id: 33669181,
            },
            original_price: null,
            category_id: 'MLU1055',
            official_store_id: null,
            catalog_product_id: 'MLU13550363',
            tags: [
                'extended_warranty_eligible',
                'good_quality_picture',
                'good_quality_thumbnail',
                'immediate_payment',
                'cart_eligible',
            ],
            catalog_listing: true,
        },
        {
            id: 'MLU811601010',
            site_id: 'MLU',
            title: 'iPhone 15 Dual Sim 512 Gb Negro',
            seller: {
                id: 451257294,
                power_seller_status: null,
                car_dealer: false,
                real_estate_agency: false,
                tags: [],
            },
            price: 41999, // Price in Uruguayan Pesos (UYU)
            currency_id: 'UYU',
            available_quantity: 1,
            sold_quantity: 1,
            buying_mode: 'buy_it_now',
            listing_type_id: 'gold_pro',
            stop_time: '2039-08-22T04:00:00.000Z',
            condition: 'new',
            permalink: 'https://www.mercadolibre.com.ar/p/MLU13550363',
            thumbnail: 'http://MLU-s1-p.mlstatic.com/943469-MLU31002769183_062019-I.jpg',
            accepts_mercadopago: true,
            installments: {
                quantity: 6,
                amount: 6999.83, // Monthly installment in UYU
                rate: 0,
                currency_id: 'UYU',
            },
            address: {
                state_id: 'AR-B',
                state_name: 'Buenos Aires',
                city_id: 'TUxBQ0dFTjY4NTg',
                city_name: 'General Rodríguez',
            },
            shipping: {
                free_shipping: true,
                mode: 'me2',
                tags: ['mandatory_free_shipping'],
                logistic_type: 'drop_off',
                store_pick_up: false,
            },
            seller_address: {
                country: {
                    id: 'AR',
                    name: 'Argentina',
                },
                state: {
                    id: 'AR-B',
                    name: 'Buenos Aires',
                },
                city: {
                    id: 'TUxBQ0dFTjY4NTg',
                    name: 'General Rodríguez',
                },
                latitude: '',
                longitude: '',
            },
            attributes: [
                {
                    values: [
                        {
                            source: 1,
                            id: '206',
                            name: 'Apple',
                            struct: null,
                        },
                    ],
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    id: 'BRAND',
                    value_id: '206',
                    value_name: 'Apple',
                    value_struct: null,
                    source: 1,
                    name: 'Marca',
                },
                {
                    id: 'CPU_MODEL',
                    value_struct: null,
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '7657686',
                            name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo de CPU',
                    value_id: '7657686',
                    value_name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                },
                {
                    values: [
                        {
                            name: 'Nuevo',
                            struct: null,
                            source: 8342579661593500,
                            id: '2230284',
                        },
                    ],
                    id: 'ITEM_CONDITION',
                    value_struct: null,
                    value_name: 'Nuevo',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 8342579661593500,
                    name: 'Condición del ítem',
                    value_id: '2230284',
                },
                {
                    value_id: '58993',
                    value_name: 'iPhone',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 1,
                    id: 'LINE',
                    name: 'Línea',
                    value_struct: null,
                    values: [
                        {
                            source: 1,
                            id: '58993',
                            name: 'iPhone',
                            struct: null,
                        },
                    ],
                },
                {
                    value_name: 'iPhone 15',
                    values: [
                        {
                            id: '6047739',
                            name: 'iPhone 15',
                            struct: null,
                            source: 1,
                        },
                    ],
                    id: 'MODEL',
                    name: 'Modelo',
                    value_id: '6047739',
                    source: 1,
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                },
                {
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '2087879',
                            name: 'Apple A15 Bionic',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo del procesador',
                    value_name: 'Apple A15 Bionic',
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                    id: 'PROCESSOR_MODEL',
                    value_id: '2087879',
                },
            ],
            differential_pricing: {
                id: 33669181,
            },
            original_price: null,
            category_id: 'MLU1055',
            official_store_id: null,
            catalog_product_id: 'MLU13550363',
            tags: [
                'extended_warranty_eligible',
                'good_quality_picture',
                'good_quality_thumbnail',
                'immediate_payment',
                'cart_eligible',
            ],
            catalog_listing: true,
        },
        {
            id: 'MLU811601010',
            site_id: 'MLU',
            title: 'iPhone 15 Dual Sim 128 Gb Negro',
            seller: {
                id: 451257294,
                power_seller_status: null,
                car_dealer: false,
                real_estate_agency: false,
                tags: [],
            },
            price: 41999, // Price in Uruguayan Pesos (UYU)
            currency_id: 'UYU',
            available_quantity: 1,
            sold_quantity: 1,
            buying_mode: 'buy_it_now',
            listing_type_id: 'gold_pro',
            stop_time: '2039-08-22T04:00:00.000Z',
            condition: 'new',
            permalink: 'https://www.mercadolibre.com.ar/p/MLU13550363',
            thumbnail: 'http://MLU-s1-p.mlstatic.com/943469-MLU31002769183_062019-I.jpg',
            accepts_mercadopago: true,
            installments: {
                quantity: 6,
                amount: 6999.83, // Monthly installment in UYU
                rate: 0,
                currency_id: 'UYU',
            },
            address: {
                state_id: 'AR-B',
                state_name: 'Buenos Aires',
                city_id: 'TUxBQ0dFTjY4NTg',
                city_name: 'General Rodríguez',
            },
            shipping: {
                free_shipping: true,
                mode: 'me2',
                tags: ['mandatory_free_shipping'],
                logistic_type: 'drop_off',
                store_pick_up: false,
            },
            seller_address: {
                country: {
                    id: 'AR',
                    name: 'Argentina',
                },
                state: {
                    id: 'AR-B',
                    name: 'Buenos Aires',
                },
                city: {
                    id: 'TUxBQ0dFTjY4NTg',
                    name: 'General Rodríguez',
                },
                latitude: '',
                longitude: '',
            },
            attributes: [
                {
                    values: [
                        {
                            source: 1,
                            id: '206',
                            name: 'Apple',
                            struct: null,
                        },
                    ],
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    id: 'BRAND',
                    value_id: '206',
                    value_name: 'Apple',
                    value_struct: null,
                    source: 1,
                    name: 'Marca',
                },
                {
                    id: 'CPU_MODEL',
                    value_struct: null,
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '7657686',
                            name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo de CPU',
                    value_id: '7657686',
                    value_name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                },
                {
                    values: [
                        {
                            name: 'Nuevo',
                            struct: null,
                            source: 8342579661593500,
                            id: '2230284',
                        },
                    ],
                    id: 'ITEM_CONDITION',
                    value_struct: null,
                    value_name: 'Nuevo',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 8342579661593500,
                    name: 'Condición del ítem',
                    value_id: '2230284',
                },
                {
                    value_id: '58993',
                    value_name: 'iPhone',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 1,
                    id: 'LINE',
                    name: 'Línea',
                    value_struct: null,
                    values: [
                        {
                            source: 1,
                            id: '58993',
                            name: 'iPhone',
                            struct: null,
                        },
                    ],
                },
                {
                    value_name: 'iPhone 15',
                    values: [
                        {
                            id: '6047739',
                            name: 'iPhone 15',
                            struct: null,
                            source: 1,
                        },
                    ],
                    id: 'MODEL',
                    name: 'Modelo',
                    value_id: '6047739',
                    source: 1,
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                },
                {
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '2087879',
                            name: 'Apple A15 Bionic',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo del procesador',
                    value_name: 'Apple A15 Bionic',
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                    id: 'PROCESSOR_MODEL',
                    value_id: '2087879',
                },
            ],
            differential_pricing: {
                id: 33669181,
            },
            original_price: null,
            category_id: 'MLU1055',
            official_store_id: null,
            catalog_product_id: 'MLU13550363',
            tags: [
                'extended_warranty_eligible',
                'good_quality_picture',
                'good_quality_thumbnail',
                'immediate_payment',
                'cart_eligible',
            ],
            catalog_listing: true,
        },
        {
            id: 'MLU811601010',
            site_id: 'MLU',
            title: 'iPhone 15 Dual Sim 256 Gb Negro',
            seller: {
                id: 451257294,
                power_seller_status: null,
                car_dealer: false,
                real_estate_agency: false,
                tags: [],
            },
            price: 41999, // Price in Uruguayan Pesos (UYU)
            currency_id: 'UYU',
            available_quantity: 1,
            sold_quantity: 1,
            buying_mode: 'buy_it_now',
            listing_type_id: 'gold_pro',
            stop_time: '2039-08-22T04:00:00.000Z',
            condition: 'new',
            permalink: 'https://www.mercadolibre.com.ar/p/MLU13550363',
            thumbnail: 'http://MLU-s1-p.mlstatic.com/943469-MLU31002769183_062019-I.jpg',
            accepts_mercadopago: true,
            installments: {
                quantity: 6,
                amount: 6999.83, // Monthly installment in UYU
                rate: 0,
                currency_id: 'UYU',
            },
            address: {
                state_id: 'AR-B',
                state_name: 'Buenos Aires',
                city_id: 'TUxBQ0dFTjY4NTg',
                city_name: 'General Rodríguez',
            },
            shipping: {
                free_shipping: true,
                mode: 'me2',
                tags: ['mandatory_free_shipping'],
                logistic_type: 'drop_off',
                store_pick_up: false,
            },
            seller_address: {
                country: {
                    id: 'AR',
                    name: 'Argentina',
                },
                state: {
                    id: 'AR-B',
                    name: 'Buenos Aires',
                },
                city: {
                    id: 'TUxBQ0dFTjY4NTg',
                    name: 'General Rodríguez',
                },
                latitude: '',
                longitude: '',
            },
            attributes: [
                {
                    values: [
                        {
                            source: 1,
                            id: '206',
                            name: 'Apple',
                            struct: null,
                        },
                    ],
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    id: 'BRAND',
                    value_id: '206',
                    value_name: 'Apple',
                    value_struct: null,
                    source: 1,
                    name: 'Marca',
                },
                {
                    id: 'CPU_MODEL',
                    value_struct: null,
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '7657686',
                            name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo de CPU',
                    value_id: '7657686',
                    value_name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                },
                {
                    values: [
                        {
                            name: 'Nuevo',
                            struct: null,
                            source: 8342579661593500,
                            id: '2230284',
                        },
                    ],
                    id: 'ITEM_CONDITION',
                    value_struct: null,
                    value_name: 'Nuevo',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 8342579661593500,
                    name: 'Condición del ítem',
                    value_id: '2230284',
                },
                {
                    value_id: '58993',
                    value_name: 'iPhone',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 1,
                    id: 'LINE',
                    name: 'Línea',
                    value_struct: null,
                    values: [
                        {
                            source: 1,
                            id: '58993',
                            name: 'iPhone',
                            struct: null,
                        },
                    ],
                },
                {
                    value_name: 'iPhone 15',
                    values: [
                        {
                            id: '6047739',
                            name: 'iPhone 15',
                            struct: null,
                            source: 1,
                        },
                    ],
                    id: 'MODEL',
                    name: 'Modelo',
                    value_id: '6047739',
                    source: 1,
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                },
                {
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '2087879',
                            name: 'Apple A15 Bionic',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo del procesador',
                    value_name: 'Apple A15 Bionic',
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                    id: 'PROCESSOR_MODEL',
                    value_id: '2087879',
                },
            ],
            differential_pricing: {
                id: 33669181,
            },
            original_price: null,
            category_id: 'MLU1055',
            official_store_id: null,
            catalog_product_id: 'MLU13550363',
            tags: [
                'extended_warranty_eligible',
                'good_quality_picture',
                'good_quality_thumbnail',
                'immediate_payment',
                'cart_eligible',
            ],
            catalog_listing: true,
        },
        {
            id: 'MLU811601010',
            site_id: 'MLU',
            title: 'iPhone 15 Dual Sim 128 Gb Negro',
            seller: {
                id: 451257294,
                power_seller_status: null,
                car_dealer: false,
                real_estate_agency: false,
                tags: [],
            },
            price: 62300, // Price in Uruguayan Pesos (UYU)
            currency_id: 'UYU',
            available_quantity: 1,
            sold_quantity: 1,
            buying_mode: 'buy_it_now',
            listing_type_id: 'gold_pro',
            stop_time: '2039-08-22T04:00:00.000Z',
            condition: 'new',
            permalink: 'https://www.mercadolibre.com.ar/p/MLU13550363',
            thumbnail: 'http://MLU-s1-p.mlstatic.com/943469-MLU31002769183_062019-I.jpg',
            accepts_mercadopago: true,
            installments: {
                quantity: 6,
                amount: 6999.83, // Monthly installment in UYU
                rate: 0,
                currency_id: 'UYU',
            },
            address: {
                state_id: 'AR-B',
                state_name: 'Buenos Aires',
                city_id: 'TUxBQ0dFTjY4NTg',
                city_name: 'General Rodríguez',
            },
            shipping: {
                free_shipping: true,
                mode: 'me2',
                tags: ['mandatory_free_shipping'],
                logistic_type: 'drop_off',
                store_pick_up: false,
            },
            seller_address: {
                country: {
                    id: 'AR',
                    name: 'Argentina',
                },
                state: {
                    id: 'AR-B',
                    name: 'Buenos Aires',
                },
                city: {
                    id: 'TUxBQ0dFTjY4NTg',
                    name: 'General Rodríguez',
                },
                latitude: '',
                longitude: '',
            },
            attributes: [
                {
                    values: [
                        {
                            source: 1,
                            id: '206',
                            name: 'Apple',
                            struct: null,
                        },
                    ],
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    id: 'BRAND',
                    value_id: '206',
                    value_name: 'Apple',
                    value_struct: null,
                    source: 1,
                    name: 'Marca',
                },
                {
                    id: 'CPU_MODEL',
                    value_struct: null,
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '7657686',
                            name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo de CPU',
                    value_id: '7657686',
                    value_name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                },
                {
                    values: [
                        {
                            name: 'Nuevo',
                            struct: null,
                            source: 8342579661593500,
                            id: '2230284',
                        },
                    ],
                    id: 'ITEM_CONDITION',
                    value_struct: null,
                    value_name: 'Nuevo',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 8342579661593500,
                    name: 'Condición del ítem',
                    value_id: '2230284',
                },
                {
                    value_id: '58993',
                    value_name: 'iPhone',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 1,
                    id: 'LINE',
                    name: 'Línea',
                    value_struct: null,
                    values: [
                        {
                            source: 1,
                            id: '58993',
                            name: 'iPhone',
                            struct: null,
                        },
                    ],
                },
                {
                    value_name: 'iPhone 15',
                    values: [
                        {
                            id: '6047739',
                            name: 'iPhone 15',
                            struct: null,
                            source: 1,
                        },
                    ],
                    id: 'MODEL',
                    name: 'Modelo',
                    value_id: '6047739',
                    source: 1,
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                },
                {
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '2087879',
                            name: 'Apple A15 Bionic',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo del procesador',
                    value_name: 'Apple A15 Bionic',
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                    id: 'PROCESSOR_MODEL',
                    value_id: '2087879',
                },
            ],
            differential_pricing: {
                id: 33669181,
            },
            original_price: null,
            category_id: 'MLU1055',
            official_store_id: null,
            catalog_product_id: 'MLU13550363',
            tags: [
                'extended_warranty_eligible',
                'good_quality_picture',
                'good_quality_thumbnail',
                'immediate_payment',
                'cart_eligible',
            ],
            catalog_listing: true,
        },
        {
            id: 'MLU811601010',
            site_id: 'MLU',
            title: 'iPhone 15 Dual Sim 512 Gb Negro',
            seller: {
                id: 451257294,
                power_seller_status: null,
                car_dealer: false,
                real_estate_agency: false,
                tags: [],
            },
            price: 65999, // Price in Uruguayan Pesos (UYU)
            currency_id: 'UYU',
            available_quantity: 1,
            sold_quantity: 1,
            buying_mode: 'buy_it_now',
            listing_type_id: 'gold_pro',
            stop_time: '2039-08-22T04:00:00.000Z',
            condition: 'new',
            permalink: 'https://www.mercadolibre.com.ar/p/MLU13550363',
            thumbnail: 'http://MLU-s1-p.mlstatic.com/943469-MLU31002769183_062019-I.jpg',
            accepts_mercadopago: true,
            installments: {
                quantity: 6,
                amount: 6999.83, // Monthly installment in UYU
                rate: 0,
                currency_id: 'UYU',
            },
            address: {
                state_id: 'AR-B',
                state_name: 'Buenos Aires',
                city_id: 'TUxBQ0dFTjY4NTg',
                city_name: 'General Rodríguez',
            },
            shipping: {
                free_shipping: true,
                mode: 'me2',
                tags: ['mandatory_free_shipping'],
                logistic_type: 'drop_off',
                store_pick_up: false,
            },
            seller_address: {
                country: {
                    id: 'AR',
                    name: 'Argentina',
                },
                state: {
                    id: 'AR-B',
                    name: 'Buenos Aires',
                },
                city: {
                    id: 'TUxBQ0dFTjY4NTg',
                    name: 'General Rodríguez',
                },
                latitude: '',
                longitude: '',
            },
            attributes: [
                {
                    values: [
                        {
                            source: 1,
                            id: '206',
                            name: 'Apple',
                            struct: null,
                        },
                    ],
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    id: 'BRAND',
                    value_id: '206',
                    value_name: 'Apple',
                    value_struct: null,
                    source: 1,
                    name: 'Marca',
                },
                {
                    id: 'CPU_MODEL',
                    value_struct: null,
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '7657686',
                            name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo de CPU',
                    value_id: '7657686',
                    value_name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                },
                {
                    values: [
                        {
                            name: 'Nuevo',
                            struct: null,
                            source: 8342579661593500,
                            id: '2230284',
                        },
                    ],
                    id: 'ITEM_CONDITION',
                    value_struct: null,
                    value_name: 'Nuevo',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 8342579661593500,
                    name: 'Condición del ítem',
                    value_id: '2230284',
                },
                {
                    value_id: '58993',
                    value_name: 'iPhone',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 1,
                    id: 'LINE',
                    name: 'Línea',
                    value_struct: null,
                    values: [
                        {
                            source: 1,
                            id: '58993',
                            name: 'iPhone',
                            struct: null,
                        },
                    ],
                },
                {
                    value_name: 'iPhone 15',
                    values: [
                        {
                            id: '6047739',
                            name: 'iPhone 15',
                            struct: null,
                            source: 1,
                        },
                    ],
                    id: 'MODEL',
                    name: 'Modelo',
                    value_id: '6047739',
                    source: 1,
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                },
                {
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '2087879',
                            name: 'Apple A15 Bionic',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo del procesador',
                    value_name: 'Apple A15 Bionic',
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                    id: 'PROCESSOR_MODEL',
                    value_id: '2087879',
                },
            ],
            differential_pricing: {
                id: 33669181,
            },
            original_price: null,
            category_id: 'MLU1055',
            official_store_id: null,
            catalog_product_id: 'MLU13550363',
            tags: [
                'extended_warranty_eligible',
                'good_quality_picture',
                'good_quality_thumbnail',
                'immediate_payment',
                'cart_eligible',
            ],
            catalog_listing: true,
        },
        {
            id: 'MLU811601010',
            site_id: 'MLU',
            title: 'iPhone 15 Dual Sim 128 Gb Negro',
            seller: {
                id: 451257294,
                power_seller_status: null,
                car_dealer: false,
                real_estate_agency: false,
                tags: [],
            },
            price: 37290, // Price in Uruguayan Pesos (UYU)
            currency_id: 'UYU',
            available_quantity: 1,
            sold_quantity: 1,
            buying_mode: 'buy_it_now',
            listing_type_id: 'gold_pro',
            stop_time: '2039-08-22T04:00:00.000Z',
            condition: 'new',
            permalink: 'https://www.mercadolibre.com.ar/p/MLU13550363',
            thumbnail: 'http://MLU-s1-p.mlstatic.com/943469-MLU31002769183_062019-I.jpg',
            accepts_mercadopago: true,
            installments: {
                quantity: 6,
                amount: 6999.83, // Monthly installment in UYU
                rate: 0,
                currency_id: 'UYU',
            },
            address: {
                state_id: 'AR-B',
                state_name: 'Buenos Aires',
                city_id: 'TUxBQ0dFTjY4NTg',
                city_name: 'General Rodríguez',
            },
            shipping: {
                free_shipping: true,
                mode: 'me2',
                tags: ['mandatory_free_shipping'],
                logistic_type: 'drop_off',
                store_pick_up: false,
            },
            seller_address: {
                country: {
                    id: 'AR',
                    name: 'Argentina',
                },
                state: {
                    id: 'AR-B',
                    name: 'Buenos Aires',
                },
                city: {
                    id: 'TUxBQ0dFTjY4NTg',
                    name: 'General Rodríguez',
                },
                latitude: '',
                longitude: '',
            },
            attributes: [
                {
                    values: [
                        {
                            source: 1,
                            id: '206',
                            name: 'Apple',
                            struct: null,
                        },
                    ],
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    id: 'BRAND',
                    value_id: '206',
                    value_name: 'Apple',
                    value_struct: null,
                    source: 1,
                    name: 'Marca',
                },
                {
                    id: 'CPU_MODEL',
                    value_struct: null,
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '7657686',
                            name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo de CPU',
                    value_id: '7657686',
                    value_name: '4x2.5 GHz Vortex/4x2.0 GHz Tempest',
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                },
                {
                    values: [
                        {
                            name: 'Nuevo',
                            struct: null,
                            source: 8342579661593500,
                            id: '2230284',
                        },
                    ],
                    id: 'ITEM_CONDITION',
                    value_struct: null,
                    value_name: 'Nuevo',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 8342579661593500,
                    name: 'Condición del ítem',
                    value_id: '2230284',
                },
                {
                    value_id: '58993',
                    value_name: 'iPhone',
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                    source: 1,
                    id: 'LINE',
                    name: 'Línea',
                    value_struct: null,
                    values: [
                        {
                            source: 1,
                            id: '58993',
                            name: 'iPhone',
                            struct: null,
                        },
                    ],
                },
                {
                    value_name: 'iPhone 15',
                    values: [
                        {
                            id: '6047739',
                            name: 'iPhone 15',
                            struct: null,
                            source: 1,
                        },
                    ],
                    id: 'MODEL',
                    name: 'Modelo',
                    value_id: '6047739',
                    source: 1,
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    attribute_group_name: 'Otros',
                },
                {
                    values: [
                        {
                            struct: null,
                            source: 6587939990796619,
                            id: '2087879',
                            name: 'Apple A15 Bionic',
                        },
                    ],
                    attribute_group_name: 'Otros',
                    name: 'Modelo del procesador',
                    value_name: 'Apple A15 Bionic',
                    value_struct: null,
                    attribute_group_id: 'OTHERS',
                    source: 6587939990796619,
                    id: 'PROCESSOR_MODEL',
                    value_id: '2087879',
                },
            ],
            differential_pricing: {
                id: 33669181,
            },
            original_price: null,
            category_id: 'MLU1055',
            official_store_id: null,
            catalog_product_id: 'MLU13550363',
            tags: [
                'extended_warranty_eligible',
                'good_quality_picture',
                'good_quality_thumbnail',
                'immediate_payment',
                'cart_eligible',
            ],
            catalog_listing: true,
        },
    ],
}
