export interface Item {
    id: number
    price: number
    name: string
    description: string
    seller: string
    sellerStars: number
    productPhotoUrl: string
}

export const items: Item[] = [
    {
        id: 1,
        price: 49.99,
        name: 'Product 1',
        description: 'This is the description for Product 1',
        seller: 'Seller 1',
        sellerStars: 4,
        productPhotoUrl: 'https://example.com/product1.jpg',
    },
    {
        id: 2,
        price: 29.99,
        name: 'Product 2',
        description: 'This is the description for Product 2',
        seller: 'Seller 2',
        sellerStars: 3,
        productPhotoUrl: 'https://example.com/product2.jpg',
    },
    {
        id: 3,
        price: 79.99,
        name: 'Product 3',
        description: 'This is the description for Product 3',
        seller: 'Seller 3',
        sellerStars: 5,
        productPhotoUrl: 'https://example.com/product3.jpg',
    },
    {
        id: 4,
        price: 39.99,
        name: 'Product 4',
        description: 'This is the description for Product 4',
        seller: 'Seller 4',
        sellerStars: 4.5,
        productPhotoUrl: 'https://example.com/product4.jpg',
    },
    {
        id: 5,
        price: 59.99,
        name: 'Product 5',
        description: 'This is the description for Product 5',
        seller: 'Seller 5',
        sellerStars: 4,
        productPhotoUrl: 'https://example.com/product5.jpg',
    },
    {
        id: 6,
        price: 69.99,
        name: 'Product 6',
        description: 'This is the description for Product 6',
        seller: 'Seller 6',
        sellerStars: 4.2,
        productPhotoUrl: 'https://example.com/product6.jpg',
    },
    {
        id: 7,
        price: 19.99,
        name: 'Product 7',
        description: 'This is the description for Product 7',
        seller: 'Seller 7',
        sellerStars: 3.8,
        productPhotoUrl: 'https://example.com/product7.jpg',
    },
    {
        id: 8,
        price: 89.99,
        name: 'Product 8',
        description: 'This is the description for Product 8',
        seller: 'Seller 8',
        sellerStars: 4.9,
        productPhotoUrl: 'https://example.com/product8.jpg',
    },
    {
        id: 9,
        price: 44.99,
        name: 'Product 9',
        description: 'This is the description for Product 9',
        seller: 'Seller 9',
        sellerStars: 4.7,
        productPhotoUrl: 'https://example.com/product9.jpg',
    },
    {
        id: 10,
        price: 59.99,
        name: 'Product 10',
        description: 'This is the description for Product 10',
        seller: 'Seller 10',
        sellerStars: 4.4,
        productPhotoUrl: 'https://example.com/product10.jpg',
    },
    {
        id: 11,
        price: 49.99,
        name: 'Product 1',
        description: 'This is the description for Product 1',
        seller: 'Seller 1',
        sellerStars: 4,
        productPhotoUrl: 'https://example.com/product1.jpg',
    },
    {
        id: 12,
        price: 29.99,
        name: 'Product 2',
        description: 'This is the description for Product 2',
        seller: 'Seller 2',
        sellerStars: 3,
        productPhotoUrl: 'https://example.com/product2.jpg',
    },
    {
        id: 13,
        price: 79.99,
        name: 'Product 3',
        description: 'This is the description for Product 3',
        seller: 'Seller 3',
        sellerStars: 5,
        productPhotoUrl: 'https://example.com/product3.jpg',
    },
    {
        id: 14,
        price: 39.99,
        name: 'Product 4',
        description: 'This is the description for Product 4',
        seller: 'Seller 4',
        sellerStars: 4.5,
        productPhotoUrl: 'https://example.com/product4.jpg',
    },
    {
        id: 15,
        price: 59.99,
        name: 'Product 5',
        description: 'This is the description for Product 5',
        seller: 'Seller 5',
        sellerStars: 4,
        productPhotoUrl: 'https://example.com/product5.jpg',
    },
    {
        id: 16,
        price: 69.99,
        name: 'Product 6',
        description: 'This is the description for Product 6',
        seller: 'Seller 6',
        sellerStars: 4.2,
        productPhotoUrl: 'https://example.com/product6.jpg',
    },
    {
        id: 17,
        price: 19.99,
        name: 'Product 7',
        description: 'This is the description for Product 7',
        seller: 'Seller 7',
        sellerStars: 3.8,
        productPhotoUrl: 'https://example.com/product7.jpg',
    },
    {
        id: 18,
        price: 89.99,
        name: 'Product 8',
        description: 'This is the description for Product 8',
        seller: 'Seller 8',
        sellerStars: 4.9,
        productPhotoUrl: 'https://example.com/product8.jpg',
    },
    {
        id: 19,
        price: 44.99,
        name: 'Product 9',
        description: 'This is the description for Product 9',
        seller: 'Seller 9',
        sellerStars: 4.7,
        productPhotoUrl: 'https://example.com/product9.jpg',
    },
    {
        id: 20,
        price: 59.99,
        name: 'Product 10',
        description: 'This is the description for Product 10',
        seller: 'Seller 10',
        sellerStars: 4.4,
        productPhotoUrl: 'https://example.com/product10.jpg',
    },
]
